# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b07329cb0fadb963446e9a2f204b77ab1fff35bf6e79de6e4c6eae4ee014a8ca5ea4b849766456213bad9624d53b250ce2737a7e248c944e07d6c1a69a5a51a0

test:
  secret_key_base: 3120ac77081e612644e833bb6827e8eddb15f897fdebdb1d1bc6d21d2a74ba92b292e24c22963b53f1056646a74cd7842006b6b2c6a4aaa99c940948d42a1ea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
